ProjectName: 'mnist_x250_2x/'
Model: 'model/'  
File: 'train_log/'
Results: './results/'
hr_files: '/cluster/project0/IQT_Nigeria/skim/HCP_Harry_x4/train/*/T1w/T1w_acpc_dc_restore_brain_sim036T_4x_groundtruth_norm.nii.gz'
lr_files: '/cluster/project0/IQT_Nigeria/skim/HCP_Harry_x4/train/*/T1w/lr_norm*.gz'
hr_files_test: '/cluster/project0/IQT_Nigeria/skim/HCP_Harry_x4/valid_small/*/T1w/T1w_acpc_dc_restore_brain_sim036T_4x_groundtruth_norm.nii.gz'
lr_files_test: '/cluster/project0/IQT_Nigeria/skim/HCP_Harry_x4/valid_small/*/T1w/lr_norm*.gz'
mri_files: '/cluster/project0/IQT_Nigeria/skim/BRATS-2/Synthetic_Data/*/*/'
pred_objective: 'pred_x0'
img_size: 28
train: True
timestep: 250
dim: 32
mean_t1: 560.5572
std_t1: 968.2950
mean_t2: 426.0168
std_t2: 771.2276
mean_flair: 367.3117
std_flair: 680.8201
mnist_path: './MNIST/raw/train-images-idx3-ubyte'
mnist_labels_path: './MNIST/raw/train-labels-idx1-ubyte'
mask_cond: False
mask_x: False
cond: 'IN'
